### PR TITLE
Implemented way to allow for partial updates/partial inputs

### PR DESCRIPTION
**Pull request by bsara**
I've implemented a way to handle partial updates. One real problem using a strongly typed language to implement a GraphQL server is the fact that you can't easily tell whether or not a client specifically set the property of an input to `null` or if they just omitted the value entirely from the query. Using [delegated properties](https://kotlinlang.org/docs/reference/delegated-properties.html), I've provided a new base class for inputs that allow for omitting some input properties: `GraphQLInput`. The usage of this in Java (as opposed to Kotlin) isn't very pretty, but should work _(I have yet to do much testing of the Java implementation of this and could use help with it because of personal time constraints)_. I also added docs for these additions to the README, though it could use a proof read.

I am aware that the project uses `reflectasm` for it's reflection. I'm not familiar with the library and could use some help converting the Kotlin reflection code that I've written to use `reflectasm` instead.

All in all, I understand that some more work here may need to be done, but for the time being this solution will work for most use cases and can be upgraded/expanded to handle more fairly easily.

I hope that this is a helpful addition to the project and expect (and welcome) feedback about things that need to be changed in order to ultimately get the changes merged.

### CODE REVIEW

**Comment by oliemansm** [comment]
@bsara 
Thank you very much for the work you've put into creating this solution! Apologies for my late response. Didn't get around to taking a look at this earlier because of my own time constraints.

Since [release 5.3.4](https://github.com/graphql-java-kickstart/graphql-java-tools/releases/tag/v5.3.4) we have improved support for using `Map` representing types and inputs as well. So instead of having to define a concrete class to represent the `input` you could let a `Map` represent it as follows:
```java
public Human createHuman(Map<String,String> createHumanInput) {
    String name = null;
    if (createHumanInput.containsKey("name")) {
        name = createHumanInput.get("name");
    }
    String homePlanet = "Jakku";
    if (createHumanInput.containsKey("homePlanet")) {
        homePlanet = createHumanInput.get("homePlanet");
    }
    return new Human(UUID.randomUUID().toString(), name, null, homePlanet);
}
```
What would this example look like if you would use your proposed solution? Because it feels like it would require a bit more boilerplate (in Java) than this actually, but haven't tried it.

**Comment by bsara** [comment]
@oliemansm Thanks so much for the reply. The solution that I am proposing would remove the tedium of setting each value manually. It does, however, require one to define a concrete input class.

Below, you'll find your example with the solution I've provided:

_Kotlin Code:_
```kotlin
class HumanMutationInput : GraphQLInput() {
  var name: String? by prop()
  var homePlanet: String? by prop()
}

fun createHuman(createHumanInput: HumanMutationInput): Human {
  return copyFromInput(createHumanInput, Human(UUID.randomUUID().toString())
}
```

Admittedly, it's pretty verbose if one were to use Java (verbose enough for me to consider another solution for small projects, larger ones might be worth it to me):

_Java Code:_
```java
class HumanMutationInput extends GraphQLInput {
  private GraphQLInputJavaPropDelegate<String> nameDelegate;
  private GraphQLInputJavaPropDelegate<String> homePlanetDelegate;

  public HumanMutationInput() {
    this.nameDelegate = this.javaProp("name");
    this.homePlanetDelegate = this.javaProp("homePlanet");
  }

  public String getName() {
    return this.nameDelegate.getValue(this);
  }

  public void setName(String name) {
    this.nameDelegate.setValue(this, name);
  }

  public String getHomePlanet() {
    return this.homePlanetDelegate.getValue(this);
  }

  public void setHomePlanet(String homePlanet) {
    this.homePlanetDelegate.setValue(this, homePlanet);
  }
}

public Human createHuman(HumanMutationInput createHumanInput) {
  return copyFromInput(createHumanInput, new Human(UUID.randomUUID().toString()));
}
```

All in all, this solution **by far** benefits users of Kotlin more than it benefits those using Java. Perhaps the recommendation could be to use `Map` for Java implementations and the property delegates for `Kotlin` with `Map` still being an option?

**Comment by bsara** [comment]
Now that I see the `Map` solution, it gets me thinking. Another potential solution could be to use reflection on the given `Map` to set values on a given object. This would not require the input class boilerplate, and it would remove the tedium of setting everything manually. This could be a very viable solution for both Java and Kotlin too as the implementation in both would be identical.

**Comment by oliemansm** [comment]
@bsara The Kotlin code definitely looks much better than the Java version :). Agreed with your second idea to use reflection as a solution that would work nicely for both to solve that use case. Your use case is comparable to using `BeanUtils.copyProperties(source, target);` while supporting partial updates, right? So you could simply fetch an entity from a database for example and call a copy method like `copyAvailableProperties(inputMap, target);` to update those values that have been provided in the update.

**Comment by bsara** [comment]
@oliemansm Yes, it is essentially the same as `BeanUtils.copyProperties`...but a little more powerful because you can give some custom mapping information to `copyFromInput` in cases where you don't have 1:1 property name mapping.

**Pull request closed without merging**
